name: CI
run-name: ${{ github.actor }} is testing out GitHub Actions
on:
  push:
    branches: [master]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'master'
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: install modules
        run: npm install
      - name: build project
        run: npm run build:prod
      - name: linting typescript
        run: npm run lint:ts
        if: always()
      - name: linting scss
        run: npm run lint:scss
        if: always()
      - name: testing unit
        run: npm run test:unit
        if: always()
      - name: update ui
        run: npm run test:ui:update
        if: always()
      - name: build storybook
        run: npm run storybook:build
        if: always()
      - name: testing ui
        run: npm run test:ui:ci
        if: always()